version: 2.1

jobs:
  build:
    environment:
      - JOB: check_style
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - run:
          name: build script
          command: paddle/scripts/paddle_docker_build.sh ${JOB}
