version: 2.1

jobs:
  build:
    environment:
      - JOB: check_style
    machine: true
    steps:
      - checkout
      - run:
          name: pre install
          command: |
            sudo pip install pylint pytest astroid isort
            function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
      - run:
          name: build script
          command: |            
            # 43min timeout
            paddle/scripts/paddle_docker_build.sh ${JOB}
            if [ $? -eq 0 ] || [ $? -eq 142 ]; then true; else exit 1; fi;
